export const mockDataOpts = {
  rows: [
    {
      values: [
        "1425022273",
        "Keyword Lasso",
        "digital marketing usa",
        "21022326167",
        "DND - Reporting product campaign",
        "162493895201",
        "RSA & Reporting kws Ad group",
        "28",
        "3",
        "0.93",
        "0",
        "0",
        "0.01",
        "0.11",
        "",
        "",
        "",
        "",
        "",
        "",
        {
          q: "digital marketing usa",
          ai: "162493895201",
          ci: "21022326167",
          cv: "0",
          cl: "3",
          im: "28",
          co: "0.93",
          cvv: "0",
          an: "RSA & Reporting kws Ad group",
          max_cpc: "0.01",
          ct: "0.11",
          bst: "",
          urls: "",
          cmpn: "DND - Reporting product campaign",
        },
      ],
    },
    {
      values: [
        "1425022273",
        "AB Testing Pause Ads",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "344642359159",
        {
          l_h: "",
          l_du: "",
          l_d1: "",
          l_d2: "",
          l_im: 241,
          l_cl: 72,
          l_intr: 72,
          l_co: 21.6,
          l_cv: 0,
          l_cvv: 0,
          l_atip: 0.5987654320987654,
          l_cmpn: "Competitors- New",
          l_cmpi: "323037738",
          l_i: "344642359159",
          l_wctr: -1,
          l_wcvcl: 0,
          l_wcvim: 0,
          l_wcvvim: 0,
          l_wcvvco: 0,
          l_wcpa: 0,
          l_watip: 0,
          l_an: "SKAG: ninja cat ppc",
          l_ai: "29198183058",
          l_agKey: "29198183058",
          l_tu: "https://www.optmyzr.com",
          l_mobileUrl: "",
          l_iu: "",
          l_h1: "Optmyzr",
          l_h2: "Workflows for PPC Pros",
          l_h3: "Free Trial Available",
          l_d: "Optmyzr AdWords Tools. Optimization Solutions, Quality Score Tracker",
          l_etad2: "Landing Page Checker, and more. Free Trial Available.",
          l_p1: "",
          l_p2: "",
          l_labels: "",
          l_rsaHeadline: "",
          l_rsaDesc: "",
          l_rsaPath1: "",
          l_rsaPath2: "",
          l_rdaHeadline: "",
          l_rdaDesc: "",
          l_rdalongHeadline: "",
          l_adType: "EXPANDED_TEXT_AD",
          l_urlSuffix: "",
          l_trackingUrl: "",
          l_customParam: "{}",
          l_busName: null,
          l_vu: null,
          l_cntCode: null,
          l_phone: null,
          w_h: "",
          w_du: "",
          w_d1: "",
          w_d2: "",
          w_im: 440,
          w_cl: 165,
          w_intr: 165,
          w_co: 62.31,
          w_cv: 0,
          w_cvv: 0,
          w_atip: 0.5660377358490566,
          w_cmpn: "Competitors- New",
          w_cmpi: "323037738",
          w_i: "344667211892",
          w_wctr: 1,
          w_wcvcl: 0,
          w_wcvim: 0,
          w_wcvvim: 0,
          w_wcvvco: 0,
          w_wcpa: 0,
          w_watip: 0,
          w_an: "SKAG: ninja cat ppc",
          w_ai: "29198183058",
          w_agKey: "29198183058",
          w_tu: "https://www.optmyzr.com",
          w_mobileUrl: "",
          w_iu: "",
          w_h1: "Optmyzr",
          w_h2: "Leading Adwords Optimization",
          w_h3: "Data Insights",
          w_d: "Optmyzr AdWords Tools. Optimization Solutions, Quality Score Tracker",
          w_etad2: "Landing Page Checker, and more. Free Trial Available.",
          w_p1: "",
          w_p2: "",
          w_labels: "",
          w_rsaHeadline: "",
          w_rsaDesc: "",
          w_rsaPath1: "",
          w_rsaPath2: "",
          w_rdaHeadline: "",
          w_rdaDesc: "",
          w_rdalongHeadline: "",
          w_adType: "EXPANDED_TEXT_AD",
          w_urlSuffix: "",
          w_trackingUrl: "",
          w_customParam: "{}",
          w_busName: null,
          w_vu: null,
          w_cntCode: null,
          w_phone: null,
          reason: "ctr",
          ad_count: 3,
        },
      ],
    },
  ],
  columns: [
    {
      defaultAggregationType: "NONE",
      name: "accountId",
      label: "Account Id",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "toolName",
      label: "Tool Name",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "query",
      label: "Query",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "campaignId",
      label: "Campaign Id",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "campaignName",
      label: "Campaign Name",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "adGroupId",
      label: "Ad Group Id",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "adGroupName",
      label: "Ad Group Name",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "impressions",
      label: "Impressions",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "clicks",
      label: "Clicks",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "cost",
      label: "Cost",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "conv",
      label: "Conv.",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "convVal",
      label: "Conv. Val.",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "maxCpc",
      label: "Max Cpc",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "ctr",
      label: "Ctr",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "biddingStrategy",
      label: "Bidding Strategy",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "kwMatchType",
      label: "Kw Match Type",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "topUrl",
      label: "Top Url",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "assetGroupId",
      label: "Asset Group Id",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "assetGroupName",
      label: "Asset Group Name",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "adId",
      label: "Ad Id",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
    {
      defaultAggregationType: "NONE",
      name: "adData",
      label: "Ad Details",
      dataType: "STRING",
      semantics: {
        conceptType: "DIMENSION",
      },
    },
  ],
};
